New designs
fida-services/website pull request #16
Opened 2024-06-17 06:40 UTC by vercia

2024-06-26 10:53 UTC, kryptt commented
This is looking great!

2024-06-26 11:18 UTC, kryptt requested changes
Some details I noticed

2024-06-26 11:18 UTC, kryptt commented on src/data/menuItems.ts
> +      link: 'https://docs.fida.finance/whitepaper.pdf',
Correct link is "https://docs.fida.finance/introduction/whitepaper"

2024-06-26 11:18 UTC, kryptt commented on src/data/socials.ts
> +    link: 'https://discord.gg/BN4NJebn'
Is this link valid? "https://discord.com/invite/kFdXXBqwdu" however does work

2024-06-26 11:18 UTC, kryptt commented on dictionary.txt
> +seemlessAIMobile
It is actually spelled Seamless  so there's probably a typo! :D

2024-06-26 11:18 UTC, kryptt commented on dictionary.txt
> +rose
"rose" wasn't in the default dictionary?! that's wierd

2024-06-26 11:18 UTC, kryptt commented on dictionary.txt
> +amet.
where was this used? feels weird and I only see it in this file

2024-06-26 11:18 UTC, kryptt commented on dictionary.txt
> +seemlessAITexts
here it shows up again

2024-06-26 11:18 UTC, kryptt commented on src/data/texts.ts
> +    description: 'Market value',
exptected APY

16-54%

2024-06-26 11:18 UTC, kryptt commented on src/data/texts.ts
> +    description: 'Insurance gap',
Launch Policies
3

2024-06-26 11:40 UTC, vercia commented on dictionary.txt
> +amet.
Yeah, that was in temporary "Lorem ipsum" text, my bad 😅 thanks for CR

2024-07-04 13:17 UTC, kryptt approved these changes

2024-07-04 13:17 UTC, kryptt commented on src/data/texts.ts
> +    { value: '$ 10 tn/FT', label: 'Estimated gap' },
{ value: ''$ 10 tn', label: 'FT Estimated gap' }

2024-07-04 13:28 UTC, merged